name: Android CI

on:
  push:
    branches: [ "development" ]
  pull_request:
    branches: [ "development" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Set up Java JDK 11
      uses: actions/setup-java@v3
      with:
        java-version: "1.8"
        # cache: gradle
    - name: Setup Node
      uses: actions/setup-node@v3
      with:
        node-version: "12"
    - name: Setup Android SDK
      uses: android-actions/setup-android@v2

    # - name: Install fontawesome
    #   run: |
    #     npm config set "@fortawesome:registry" https://npm.fontawesome.com/
    - name: Install dependencies
      run: |
        npm install
        # sudo apt update
        # sudo apt install -y ccache
    - name: Grant execute permission for gradlew
      run: cd android && chmod +x gradlew
    - name: Build with Gradle
      # run: cd android && $ ./gradlew :app:assembleDebug -PreactNativeArchitectures=x86_64
      run: cd android && $ ./gradlew app:bundleRelease -PreactNativeArchitectures=x86_64
